// COMMON - GETTERS
export const GET_TABLIST = 'GET_TABLIST';

// PIZZALIST - GETTERS
export const GET_PIZZALIST = 'GET_PIZZALIST';

// PIZZALIST - ACTIONS
export const FETCH_PIZZALIST = 'FETCH_PIZZALIST';

// PIZZALIST - MUTATIONS
export const SET_PIZZALIST = 'SET_PIZZALIST';
