// COMMON - GETTERS
export const GET_TABLIST = 'GET_TABLIST';
export const GET_ACTIVE_TAB = 'GET_ACTIVE_TAB';

// COMMON - MUTATIONS
export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';

// PIZZALIST - GETTERS
export const GET_PIZZALIST = 'GET_PIZZALIST';

// PIZZALIST - ACTIONS
export const FETCH_PIZZALIST = 'FETCH_PIZZALIST';

// PIZZALIST - MUTATIONS
export const SET_PIZZALIST = 'SET_PIZZALIST';
